default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      # - id: no-commit-to-branch
      #   args:
      #     - --branch=main

  - repo: https://github.com/frnmst/md-toc
    rev: 8.1.1
    hooks:
      - id: md-toc
        language_version: python3


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.17.0
    hooks:
      - id: validate_manifest

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.0
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: no-go-testing
    - id: golangci-lint
    - id: go-critic
    #- id: go-unit-tests
    #- id: go-build
    - id: go-mod-tidy
